name: Update Sliv Data

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:        # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full git history
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure push permissions

      - name: Force Update Timestamp
        run: |
          # Get current IST time
          IST_TIME=$(TZ="Asia/Kolkata" date +"%I:%M %p %d-%m-%Y")
          
          # Always update the timestamp (create file if missing)
          mkdir -p sliv
          if [ ! -f sliv/data.json ]; then
            echo '{"last update time":"initial"}' > sliv/data.json
          fi
          
          # Update timestamp regardless of other content
          jq --arg time "$IST_TIME" '."last update time" = $time' sliv/data.json > tmp.json
          mv tmp.json sliv/data.json

          # Force add and commit
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f sliv/data.json
          git commit --allow-empty -m "Fetch latest live data for Sony LIV"
          git push
